[package]
name = "bchip8"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
env_logger = "0.11.8"
log = "0.4.27"
rand = "0.9.2"
ratatui = "0.29.0"
